# -*- coding: utf-8 -*-
"""docx_reader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-IESodV7yJPv_QxoWnvtJsceDo17af3
"""

from docx import Document

def read_docx(file):
    doc = Document(file)
    text = []
    for para in doc.paragraphs:
        if para.text.strip():
            text.append(para.text.strip())
    return "\n".join(text)